### ISSUE TITLE
laradock 本地多项目部署的时候，修改 docker-compose文件，build 出错

### ISSUE THREAD

**Issue by eleven0220** [dspurl/dsshop#70]
1、商城程序最新版本，从git clone下来的
2、laradock最新版本，从git clone下来的
3、docker-compose 文件：
      
        `nginx:
      build:
        context: ./nginx
        args:
          - CHANGE_SOURCE=${CHANGE_SOURCE}
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
        - "${VARNISH_BACKEND_PORT}:81"
      depends_on:
        - php-fpm
      networks:
        - frontend
          aliases:
           - hzf.local
        - backend
          aliases:
           - hzf.local`
运行命令：
`docker-compose build --no-cache nginx`
报错提示：
`yaml.scanner.ScannerError: mapping values are not allowed here
  in ".\docker-compose.yml", line 381, column 18`

**Comment by Caisen1988** [comment]
请问你本地是啥环境？Mac?
请问你381是哪一行？是宿主机权限问题吗？
![image](https://user-images.githubusercontent.com/11453160/100984610-e8f19100-3585-11eb-9a50-fbf5f5889d04.png)

**Comment by eleven0220** [comment]
windows 10 , 就是你发出来的这一行 @Caisen1988

**Comment by dspurl** [comment]
你的代码有问题，最后一行多了个``为什么`frontend`和`backend`前面会有`-`，我的docker-compose并没有
```
networks:
    - frontend
      aliases:
       - hzf.local
    - backend
      aliases:
       - hzf.local`
```
应该是这样的
```
networks:
        frontend:
         aliases:
          - hzf.local
        backend:
         aliases:
          - hzf.local
```
